### PR TITLE
Added threshold.

### PR DESCRIPTION
**Pull request by joskolenberg**
Add a threshold option to filter only relevant items.

### CODE REVIEW

**Comment by rap2hpoutre** [comment]
Thank you !!

**Comment by joskolenberg** [comment]
My pleasure, any guess on what happened to the hhvm build on travis-ci?
And any plans to publish it in a new release?

Thanks in advance.

**Comment by rap2hpoutre** [comment]
@joskolenberg I "fixed" this by dropping support for HHVM (and adding 7.3)! It's available in v1.1.0 (just released). Thank you again!

**Comment by joskolenberg** [comment]
Nice, thanks!

**Pull request merged**
